import type { ConsumerOrder } from "./orders.types";

export const mockOrders: ConsumerOrder[] = [
  {
    id: 101,
    status: "requested",
    total_price: 6000,
    pickup_code: "RVT01",
    delivery_notes: "Bite sized",
    cancel_reason: null,
    customer: {
      id: "consumer-1",
      name: "Consumer",
      phone: "3000000000",
    },
    entrepreneur: {
      id: "ent-1",
      name: "Sweet Lab",
      category: "Desserts",
      contact_info: "Near cafeteria",
      img: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=800&q=80",
      entrepreneur_position: null,
      campus_location_id: 1,
    },
    tracking: {
      estimated_distance: 10,
      estimated_time: 12,
      user_position: null,
      campus_location_id: 1,
      location_name: "Main Campus",
    },
    items: [
      {
        id: 1,
        product_id: 1,
        name: "Red velvet",
        quantity: 1,
        unit_price: 6000,
        subtotal: 6000,
        img: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=800&q=80",
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 102,
    status: "delivered",
    total_price: 4000,
    pickup_code: "CKS22",
    delivery_notes: "Bite sized",
    cancel_reason: null,
    customer: {
      id: "consumer-1",
      name: "Consumer",
      phone: "3000000000",
    },
    entrepreneur: {
      id: "ent-2",
      name: "Cookie Lab",
      category: "Bakery",
      contact_info: "Near library",
      img: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80",
      entrepreneur_position: null,
      campus_location_id: 1,
    },
    tracking: {
      estimated_distance: 20,
      estimated_time: 18,
      user_position: null,
      campus_location_id: 1,
      location_name: "Main Campus",
    },
    items: [
      {
        id: 2,
        product_id: 2,
        name: "Chip Cookies",
        quantity: 2,
        unit_price: 2000,
        subtotal: 4000,
        img: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80",
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: null,
  },
  {
    id: 103,
    status: "declined",
    total_price: 6000,
    pickup_code: "PND09",
    delivery_notes: "Coffee delivery",
    cancel_reason:
      "I have to go to the hospital, i have an emergency, sorry, im aviable tomorrow i think.",
    customer: {
      id: "consumer-1",
      name: "Consumer",
      phone: "3000000000",
    },
    entrepreneur: {
      id: "ent-3",
      name: "Pan y Cafe",
      category: "Bakery",
      contact_info: "Near arts building",
      img: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=80",
      entrepreneur_position: null,
      campus_location_id: 1,
    },
    tracking: {
      estimated_distance: 10,
      estimated_time: 10,
      user_position: null,
      campus_location_id: 1,
      location_name: "Main Campus",
    },
    items: [
      {
        id: 3,
        product_id: 3,
        name: "Pandebono",
        quantity: 1,
        unit_price: 6000,
        subtotal: 6000,
        img: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=80",
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: null,
  },
];
